from scanner import scan_port, grab_banner, run_scan

print("=" * 50)
print("TEST 1 — known open port (should return 80)")
print("=" * 50)
result = scan_port("scanme.nmap.org", 80)
print(f"Result: {result}")

print("\n" + "=" * 50)
print("TEST 2 — known closed port (should return None)")
print("=" * 50)
result = scan_port("scanme.nmap.org", 9999)
print(f"Result: {result}")

print("\n" + "=" * 50)
print("TEST 3 — port 0, below valid range (should return None)")
print("=" * 50)
result = scan_port("scanme.nmap.org", 0)
print(f"Result: {result}")

print("\n" + "=" * 50)
print("TEST 4 — port 65535, highest valid port (should return None or port)")
print("=" * 50)
result = scan_port("scanme.nmap.org", 65535)
print(f"Result: {result}")

print("\n" + "=" * 50)
print("TEST 5 — invalid IP address (should return None)")
print("=" * 50)
result = scan_port("999.999.999.999", 80)
print(f"Result: {result}")

print("\n" + "=" * 50)
print("TEST 6 — localhost port 80 (depends on your machine)")
print("=" * 50)
result = scan_port("127.0.0.1", 80)
print(f"Result: {result}")

print("\n" + "=" * 50)
print("TEST 7 — empty string as target (should return None)")
print("=" * 50)
result = scan_port("", 80)
print(f"Result: {result}")

print("\n" + "=" * 50)
print("TEST 8 — None as target (should return None)")
print("=" * 50)
result = scan_port(None, 80)
print(f"Result: {result}")

print("\n" + "=" * 50)
print("TEST 9 — string as port number (should return None)")
print("=" * 50)
result = scan_port("scanme.nmap.org", "eighty")
print(f"Result: {result}")

print("\n" + "=" * 50)
print("TEST 10 — negative port number (should return None)")
print("=" * 50)
result = scan_port("scanme.nmap.org", -1)
print(f"Result: {result}")

print("\n" + "=" * 50)
print("TEST 11 — banner grab on known open port (should return banner)")
print("=" * 50)
banner = grab_banner("scanme.nmap.org", 80)
print(f"Result: {banner}")

print("\n" + "=" * 50)
print("TEST 12 — banner grab on closed port (should return None)")
print("=" * 50)
banner = grab_banner("scanme.nmap.org", 9999)
print(f"Result: {banner}")

print("\n" + "=" * 50)
print("TEST 13 — banner grab with invalid IP (should return None)")
print("=" * 50)
banner = grab_banner("999.999.999.999", 80)
print(f"Result: {banner}")

print("\n" + "=" * 50)
print("TEST 14 — run_scan on small port range (should find open ports)")
print("=" * 50)
open_ports = run_scan("scanme.nmap.org", 79, 82, threads=10)
print(f"Open ports found: {open_ports}")

print("\n" + "=" * 50)
print("TEST 15 — run_scan with start higher than end (should find nothing)")
print("=" * 50)
open_ports = run_scan("scanme.nmap.org", 100, 1, threads=10)
print(f"Open ports found: {open_ports}")

print("\n" + "=" * 50)
print("TEST 16 — run_scan on localhost (depends on your machine)")
print("=" * 50)
open_ports = run_scan("127.0.0.1", 1, 100, threads=50)
print(f"Open ports found: {open_ports}")

print("\n" + "=" * 50)
print("TEST 17 — run_scan with 1 thread instead of 100 (slow but should work)")
print("=" * 50)
open_ports = run_scan("scanme.nmap.org", 79, 82, threads=1)
print(f"Open ports found: {open_ports}")

print("\n" + "=" * 50)
print("TEST 18 — run_scan with 1000 threads (should still work)")
print("=" * 50)
open_ports = run_scan("scanme.nmap.org", 79, 82, threads=1000)
print(f"Open ports found: {open_ports}")

print("\n" + "=" * 50)
print("TEST 19 — port 443 HTTPS (should return 443)")
print("=" * 50)
result = scan_port("scanme.nmap.org", 443)
print(f"Result: {result}")

print("\n" + "=" * 50)
print("TEST 20 — banner grab on port 22 SSH (should return SSH banner)")
print("=" * 50)
banner = grab_banner("scanme.nmap.org", 22)
print(f"Result: {banner}")